# C86 Makefile for ELKS using OpenWatcom C

############# Standard Section for Open Watcom C ##############
ifndef TOPDIR
$(error ELKS TOPDIR is not defined)
endif

ifndef WATCOM
$(error OpenWatcom WATCOM is not defined)
endif

CC = owcc
LD = owcc
CLBASE = -mcmodel=l
CLBASE += -bnone -march=i86 -std=c99
CLBASE += -fno-stack-check -fnostdlib -fsigned-char
CLBASE += -Wc,-fpc -Wc,-zev -Wc,-zls -Wc,-x -Wc,-wcd=303
WARNINGS = -Wall -Wextra
INCLUDES = -I$(TOPDIR)/libc/include -I$(TOPDIR)/elks/include
INCLUDES += -I$(TOPDIR)/libc/include/watcom
DEFINES = -D__ELKS__ -D__unix__ -DSYS16BIT -DMAX_WBITS=12 -DMAX_MEM_LEVEL=3 -DFASTEST -DMINIZIP_FOPEN_NO_64 -DNOCRYPT -DUSE_FILE32API
CFLAGS = -Os $(CLBASE) $(WARNINGS) $(INCLUDES) $(DEFINES) $(LOCALFLAGS)
LDBASE = -bos2 -s
LDBASE += -Wl,option -Wl,dosseg
LDBASE += -Wl,option -Wl,start=_start
LDBASE += -Wl,option -Wl,nodefaultlibs
LDBASE += -Wl,option -Wl,stack=0x5000
LDBASE += -Wl,option -Wl,heapsize=512
LDFLAGS = $(LDBASE)
LDLIBS = -Wl,library -Wl,$(TOPDIR)/libc/libcl.lib

OBJS = $(SRCS:.c=.obj)
%.obj: %.c
	$(CC) -c $(CFLAGS) -o $*.obj $<

############# End of Standard Section ##############

BINDIR = ../elks-bin
LOCALFLAGS = -DNDEBUG
PROG = gzip untgz
SRCS = \
     adler32.c \
     compress.c \
     crc32.c \
     deflate.c \
     gzclose.c \
     gzlib.c \
     gzread.c \
     gzwrite.c \
     infback.c \
     inffast.c \
     inflate.c \
     inftrees.c \
     trees.c \
     uncompr.c \
     zutil.c \
     mem.c \


all: $(PROG)

gzip: $(OBJS) test/minigzip.obj
	$(LD) $(LDFLAGS) -o $@ $(OBJS) test/minigzip.obj $(LDLIBS)

untgz: $(OBJS) contrib/untgz/untgz.obj
	$(LD) $(LDFLAGS) -o $@ $(OBJS) contrib/untgz/untgz.obj $(LDLIBS)


zip: $(OBJS) contrib/minizip/minizip.obj contrib/minizip/zip.obj contrib/minizip/ioapi.obj
	$(LD) $(LDFLAGS) -o $@ $(OBJS) contrib/minizip/minizip.obj contrib/minizip/zip.obj contrib/minizip/ioapi.obj $(LDLIBS)

unzip: $(OBJS) contrib/minizip/miniunz.obj contrib/minizip/unzip.obj contrib/minizip/ioapi.obj
	$(LD) $(LDFLAGS) -o $@ $(OBJS) contrib/minizip/miniunz.obj contrib/minizip/unzip.obj contrib/minizip/ioapi.obj $(LDLIBS)

#lupng: $(OBJS) test/lupng.obj
#	$(LD) $(LDFLAGS) -o $@ $(OBJS) test/lupng.obj $(LDLIBS)


test/minigzip.obj: test/minigzip.c
	$(CC) -c $(CFLAGS) -o test/minigzip.obj $<

contrib/untgz/untgz.obj: contrib/untgz/untgz.c
	$(CC) -c $(CFLAGS) -o contrib/untgz/untgz.obj $<

## lupng is almost there
#test/lupng.obj: test/lupng.c
	$(CC) -c $(CFLAGS) -o test/lupng.obj $<

contrib/minizip/minizip.obj: contrib/minizip/minizip.c
	$(CC) -c $(CFLAGS) -o contrib/minizip/minizip.obj $<

contrib/minizip/miniunz.obj: contrib/minizip/miniunz.c
	$(CC) -c $(CFLAGS) -o contrib/minizip/miniunz.obj $<

contrib/minizip/zip.obj: contrib/minizip/zip.c
	$(CC) -c $(CFLAGS) -o contrib/minizip/zip.obj $<


contrib/minizip/unzip.obj: contrib/minizip/unzip.c
	$(CC) -c $(CFLAGS) -o contrib/minizip/unzip.obj $<


contrib/minizip/ioapi.obj: contrib/minizip/ioapi.c
	$(CC) -c $(CFLAGS) -o contrib/minizip/ioapi.obj $<

clean:
	rm -f $(PROG) *.obj contrib/minizip/*.obj test/minigzip.obj contrib/untgz/untgz.obj tmp.h
